/**
 * Script pour ajouter les 50 marques stratégiques dans la base de données
 * 
 * Usage: npx tsx scripts/add-strategic-brands.ts
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Configuration des 50 marques stratégiques
const STRATEGIC_BRANDS = [
  // Mass-Market & Fast Fashion (Priorité 1 - Haute)
  {
    name: 'Zara',
    baseUrl: 'https://www.zara.com',
    newInUrl: '/fr/fr/categorie/femme/nouveautes-c358009.html',
    bestSellersUrl: '/fr/fr/categorie/femme/c358009.html',
    productSelector: '.product-item, .product-card',
    nameSelector: '.product-name, h3',
    priceSelector: '.price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'ES',
    category: 'fast_fashion',
    priority: 1,
  },
  {
    name: 'H&M',
    baseUrl: 'https://www2.hm.com',
    newInUrl: '/fr_fr/ladies/shop-by-product/view-all.html?sort=news',
    bestSellersUrl: '/fr_fr/ladies/shop-by-product/view-all.html?sort=popularity',
    productSelector: '.product-item',
    nameSelector: '.product-item-title',
    priceSelector: '.product-item-price',
    imageSelector: '.product-item-image img',
    country: 'SE',
    category: 'fast_fashion',
    priority: 1,
  },
  {
    name: 'ASOS',
    baseUrl: 'https://www.asos.com',
    newInUrl: '/new-in/ctas/?nlid=nav|header|new+in',
    bestSellersUrl: '/best-sellers/ctas/?nlid=nav|header|best+sellers',
    productSelector: 'article[data-auto-id="productTile"]',
    nameSelector: 'h3[data-auto-id="productTileTitle"]',
    priceSelector: 'span[data-auto-id="productTilePrice"]',
    imageSelector: 'img[data-auto-id="productTileImage"]',
    country: 'UK',
    category: 'fast_fashion',
    priority: 1,
  },
  {
    name: 'Uniqlo',
    baseUrl: 'https://www.uniqlo.com',
    newInUrl: '/fr/fr/new-arrivals/',
    bestSellersUrl: '/fr/fr/best-sellers/',
    productSelector: '.product-tile',
    nameSelector: '.product-tile-name',
    priceSelector: '.product-tile-price',
    imageSelector: '.product-tile-image img',
    country: 'JP',
    category: 'fast_fashion',
    priority: 1,
  },
  {
    name: 'Mango',
    baseUrl: 'https://shop.mango.com',
    newInUrl: '/fr/femme/nouveautes',
    bestSellersUrl: '/fr/femme/bestsellers',
    productSelector: '.product-item',
    nameSelector: '.product-name',
    priceSelector: '.product-price',
    imageSelector: '.product-image img',
    country: 'ES',
    category: 'fast_fashion',
    priority: 2,
  },
  {
    name: 'Bershka',
    baseUrl: 'https://www.bershka.com',
    newInUrl: '/fr/fr/femme/nouveautes-c1010193200.html',
    bestSellersUrl: '/fr/fr/femme/c1010193200.html',
    productSelector: '.product-item, .product-card',
    nameSelector: '.product-name, h3',
    priceSelector: '.price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'ES',
    category: 'fast_fashion',
    priority: 2,
  },
  {
    name: 'Pull&Bear',
    baseUrl: 'https://www.pullandbear.com',
    newInUrl: '/fr/fr/femme/nouveautes-c1010193200.html',
    bestSellersUrl: '/fr/fr/femme/c1010193200.html',
    productSelector: '.product-item, .product-card',
    nameSelector: '.product-name, h3',
    priceSelector: '.price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'ES',
    category: 'fast_fashion',
    priority: 2,
  },
  {
    name: 'Primark',
    baseUrl: 'https://www.primark.com',
    newInUrl: '/fr/fr/women/new-in',
    bestSellersUrl: '/fr/fr/women/bestsellers',
    productSelector: '.product-item, .product-card',
    nameSelector: '.product-name, h3',
    priceSelector: '.price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'IE',
    category: 'fast_fashion',
    priority: 3,
  },
  {
    name: 'Shein',
    baseUrl: 'https://www.shein.com',
    newInUrl: '/fr/new-arrivals',
    bestSellersUrl: '/fr/bestsellers',
    productSelector: '.product-item, .product-card',
    nameSelector: '.product-name, h3',
    priceSelector: '.price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'CN',
    category: 'fast_fashion',
    priority: 2,
  },

  // Sportswear & Streetwear (Priorité 1-2)
  {
    name: 'Nike',
    baseUrl: 'https://www.nike.com',
    newInUrl: '/fr/fr/new',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'US',
    category: 'sportswear',
    priority: 1,
  },
  {
    name: 'Adidas',
    baseUrl: 'https://www.adidas.fr',
    newInUrl: '/fr/nouveautes',
    bestSellersUrl: '/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'DE',
    category: 'sportswear',
    priority: 1,
  },
  {
    name: 'Puma',
    baseUrl: 'https://www.puma.com',
    newInUrl: '/fr/fr/new-arrivals',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'DE',
    category: 'sportswear',
    priority: 2,
  },
  {
    name: 'New Balance',
    baseUrl: 'https://www.newbalance.fr',
    newInUrl: '/fr/nouveautes',
    bestSellersUrl: '/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'US',
    category: 'sportswear',
    priority: 2,
  },
  {
    name: 'The North Face',
    baseUrl: 'https://www.thenorthface.fr',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'US',
    category: 'sportswear',
    priority: 2,
  },
  {
    name: 'Carhartt WIP',
    baseUrl: 'https://www.carhartt-wip.com',
    newInUrl: '/fr/new-arrivals',
    bestSellersUrl: '/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'US',
    category: 'streetwear',
    priority: 2,
  },
  {
    name: 'Dickies',
    baseUrl: 'https://www.dickieslife.com',
    newInUrl: '/fr/new-arrivals',
    bestSellersUrl: '/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'US',
    category: 'streetwear',
    priority: 3,
  },
  {
    name: 'Lacoste',
    baseUrl: 'https://www.lacoste.com',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'FR',
    category: 'sportswear',
    priority: 2,
  },
  {
    name: 'Vans',
    baseUrl: 'https://www.vans.fr',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'US',
    category: 'streetwear',
    priority: 2,
  },
  {
    name: 'Champion',
    baseUrl: 'https://www.championstore.com',
    newInUrl: '/fr/new-arrivals',
    bestSellersUrl: '/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'US',
    category: 'sportswear',
    priority: 3,
  },

  // Denim & Heritage
  {
    name: 'Levi\'s',
    baseUrl: 'https://www.levi.com',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'US',
    category: 'denim',
    priority: 1,
  },
  {
    name: 'Diesel',
    baseUrl: 'https://www.diesel.com',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'IT',
    category: 'denim',
    priority: 2,
  },
  {
    name: 'Lee',
    baseUrl: 'https://www.lee.com',
    newInUrl: '/fr/new-arrivals',
    bestSellersUrl: '/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'US',
    category: 'denim',
    priority: 3,
  },
  {
    name: 'Wrangler',
    baseUrl: 'https://www.wrangler.com',
    newInUrl: '/fr/new-arrivals',
    bestSellersUrl: '/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'US',
    category: 'denim',
    priority: 3,
  },
  {
    name: 'Calvin Klein',
    baseUrl: 'https://www.calvinklein.fr',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'US',
    category: 'premium',
    priority: 2,
  },

  // Premium & Accessible Luxury
  {
    name: 'Sandro',
    baseUrl: 'https://www.sandro-paris.com',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'FR',
    category: 'premium',
    priority: 2,
  },
  {
    name: 'Maje',
    baseUrl: 'https://www.maje.com',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'FR',
    category: 'premium',
    priority: 2,
  },
  {
    name: 'The Kooples',
    baseUrl: 'https://www.thekooples.com',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'FR',
    category: 'premium',
    priority: 2,
  },
  {
    name: 'Zadig & Voltaire',
    baseUrl: 'https://www.zadig-et-voltaire.com',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'FR',
    category: 'premium',
    priority: 2,
  },
  {
    name: 'A.P.C.',
    baseUrl: 'https://www.apc.fr',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'FR',
    category: 'premium',
    priority: 2,
  },
  {
    name: 'Jacquemus',
    baseUrl: 'https://www.jacquemus.com',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'FR',
    category: 'luxury',
    priority: 2,
  },
  {
    name: 'AMI Paris',
    baseUrl: 'https://www.amiparis.com',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'FR',
    category: 'premium',
    priority: 2,
  },
  {
    name: 'Ralph Lauren',
    baseUrl: 'https://www.ralphlauren.fr',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'US',
    category: 'premium',
    priority: 2,
  },
  {
    name: 'Tommy Hilfiger',
    baseUrl: 'https://fr.tommy.com',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'US',
    category: 'premium',
    priority: 2,
  },
  {
    name: 'Ganni',
    baseUrl: 'https://www.ganni.com',
    newInUrl: '/fr/new-arrivals',
    bestSellersUrl: '/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'DK',
    category: 'premium',
    priority: 3,
  },

  // Retailers Mondiaux
  {
    name: 'Zalando',
    baseUrl: 'https://www.zalando.fr',
    newInUrl: '/nouveautes/',
    bestSellersUrl: '/best-sellers/',
    productSelector: '.z-nvg-catalog_articles-article',
    nameSelector: '.z-nvg-catalog_articles-article-name',
    priceSelector: '.z-nvg-catalog_articles-article-price',
    imageSelector: '.z-nvg-catalog_articles-article-image img',
    country: 'DE',
    category: 'marketplace',
    priority: 1,
  },
  {
    name: 'Boohoo',
    baseUrl: 'https://fr.boohoo.com',
    newInUrl: '/new-in',
    bestSellersUrl: '/bestsellers',
    productSelector: '.product-item, .product-card',
    nameSelector: '.product-name, h3',
    priceSelector: '.price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'UK',
    category: 'fast_fashion',
    priority: 2,
  },
  {
    name: 'Urban Outfitters',
    baseUrl: 'https://www.urbanoutfitters.com',
    newInUrl: '/new-arrivals',
    bestSellersUrl: '/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'US',
    category: 'fast_fashion',
    priority: 2,
  },
  {
    name: 'Decathlon',
    baseUrl: 'https://www.decathlon.fr',
    newInUrl: '/fr/nouveautes',
    bestSellersUrl: '/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'FR',
    category: 'sportswear',
    priority: 3,
  },
  {
    name: 'Galeries Lafayette',
    baseUrl: 'https://www.galerieslafayette.com',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'FR',
    category: 'marketplace',
    priority: 3,
  },

  // Luxe (Tendances de fond)
  {
    name: 'Louis Vuitton',
    baseUrl: 'https://www.louisvuitton.com',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'FR',
    category: 'luxury',
    priority: 3,
  },
  {
    name: 'Gucci',
    baseUrl: 'https://www.gucci.com',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'IT',
    category: 'luxury',
    priority: 3,
  },
  {
    name: 'Prada',
    baseUrl: 'https://www.prada.com',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'IT',
    category: 'luxury',
    priority: 3,
  },
  {
    name: 'Balenciaga',
    baseUrl: 'https://www.balenciaga.com',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'ES',
    category: 'luxury',
    priority: 3,
  },
  {
    name: 'Stone Island',
    baseUrl: 'https://www.stoneisland.com',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'IT',
    category: 'luxury',
    priority: 3,
  },
  {
    name: 'Off-White',
    baseUrl: 'https://www.off---white.com',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'US',
    category: 'luxury',
    priority: 3,
  },
  {
    name: 'Supreme',
    baseUrl: 'https://www.supreme.com',
    newInUrl: '/shop/new',
    bestSellersUrl: '/shop/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'US',
    category: 'luxury',
    priority: 3,
  },
  {
    name: 'Celine',
    baseUrl: 'https://www.celine.com',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'FR',
    category: 'luxury',
    priority: 3,
  },
  {
    name: 'Saint Laurent',
    baseUrl: 'https://www.ysl.com',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'FR',
    category: 'luxury',
    priority: 3,
  },
  {
    name: 'Moncler',
    baseUrl: 'https://www.moncler.com',
    newInUrl: '/fr/fr/nouveautes',
    bestSellersUrl: '/fr/fr/bestsellers',
    productSelector: '.product-card, .product-tile',
    nameSelector: '.product-title, h3',
    priceSelector: '.product-price, [data-price]',
    imageSelector: '.product-image img, img[data-src]',
    country: 'IT',
    category: 'luxury',
    priority: 3,
  },
];

async function main() {
  console.log('🚀 Ajout des 50 marques stratégiques...\n');

  let added = 0;
  let updated = 0;
  let skipped = 0;

  for (const brand of STRATEGIC_BRANDS) {
    try {
      const existing = await prisma.scrapableBrand.findUnique({
        where: { name: brand.name },
      });

      if (existing) {
        // Mettre à jour si existe déjà
        await prisma.scrapableBrand.update({
          where: { name: brand.name },
          data: {
            baseUrl: brand.baseUrl,
            newInUrl: brand.newInUrl,
            bestSellersUrl: brand.bestSellersUrl,
            productSelector: brand.productSelector,
            nameSelector: brand.nameSelector,
            priceSelector: brand.priceSelector,
            imageSelector: brand.imageSelector,
            country: brand.country,
            category: brand.category,
            priority: brand.priority,
            isActive: true,
          },
        });
        updated++;
        console.log(`✅ Mis à jour: ${brand.name} (${brand.category}, priorité ${brand.priority})`);
      } else {
        // Créer si n'existe pas
        await prisma.scrapableBrand.create({
          data: {
            name: brand.name,
            baseUrl: brand.baseUrl,
            newInUrl: brand.newInUrl,
            bestSellersUrl: brand.bestSellersUrl,
            productSelector: brand.productSelector,
            nameSelector: brand.nameSelector,
            priceSelector: brand.priceSelector,
            imageSelector: brand.imageSelector,
            country: brand.country,
            category: brand.category,
            priority: brand.priority,
            isActive: true,
            notes: `Ajouté via script add-strategic-brands.ts - ${new Date().toISOString()}`,
          },
        });
        added++;
        console.log(`➕ Ajouté: ${brand.name} (${brand.category}, priorité ${brand.priority})`);
      }
    } catch (error: any) {
      console.error(`❌ Erreur pour ${brand.name}:`, error.message);
      skipped++;
    }
  }

  console.log('\n📊 Résumé:');
  console.log(`   ➕ Ajoutés: ${added}`);
  console.log(`   ✅ Mis à jour: ${updated}`);
  console.log(`   ⚠️  Ignorés: ${skipped}`);
  console.log(`   📦 Total: ${added + updated} marques configurées\n`);

  // Afficher les statistiques par catégorie
  const stats = await prisma.scrapableBrand.groupBy({
    by: ['category'],
    where: { isActive: true },
    _count: true,
  });

  console.log('📈 Répartition par catégorie:');
  for (const stat of stats) {
    console.log(`   ${stat.category || 'Non catégorisé'}: ${stat._count} marques`);
  }
}

main()
  .catch((error) => {
    console.error('❌ Erreur:', error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
